package com.example.icici.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "icici_transactions",
        indexes = {
                @Index(name = "idx_psp_txn_id", columnList = "pspTxnId"),
                @Index(name = "idx_upi_txn_id", columnList = "upiTxnId"),
                @Index(name = "idx_status", columnList = "status")
        })
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class icici_transactions {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id", nullable = false)
    private icici_accounts accountId;

    @Column(nullable = false)
    private String payerVpa;

    @Column(nullable = false)
    private String payeeVpa;

    @Column(nullable = false)
    private BigDecimal amount; // transaction amount

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType transactionType;  // DEBIT / CREDIT

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionStatus status;  // SUCCESS / FAILED / PENDING / REVERSED


    private String rrn; //NPCI reference number (for now it can be null)

    @Column(unique = true, nullable = false)
    private String pspTxnId; //transaction id of generated by psp

    @Column(unique = true)
    private String upiTxnId; //transaction id of generated by npci

    @Column(name = "failure_reason")
    private String failure_reason; // if status is FAILED, reason for failure

    private Boolean reversalInitiated = false;

    @Column(nullable = false,updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    public void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    public void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public enum TransactionType {
        DEBIT, CREDIT,REVERSED
    }

    public enum TransactionStatus {
        SUCCESS,           // Receiver credited
        FAILED,            // Failed before credit
        REVERSED           // Money credited back to sender
    }

}
