package com.example.icici.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "icici_transactions")
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class icici_transactions {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id", nullable = false)
    private icici_accounts account_id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType transactionType;  // DEBIT / CREDIT

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionStatus status;  // SUCCESS / FAILED / PENDING / REVERSED

    @Column(nullable = false)
    private Double amount; // transaction amount

    private String rrn; //NPCI reference number (for now it can be null)

    private String psp_txn_id; //transaction id of generated by psp

    private String upi_txn_id; //transaction id of generated by npci

    @Column(name = "failure_reason")
    private String failure_reason; // if status is FAILED, reason for failure

    @Column(nullable = false,updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    public void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    public void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public enum TransactionType {
        DEBIT, CREDIT
    }

    public enum TransactionStatus {
        SUCCESS, FAILED, PENDING, REVERSED
    }

}
